# Generated by Django 5.2.9 on 2025-12-09 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('proformas', '0002_proformaitem_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGItemCompliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('PARTIAL', 'Partial'), ('NA', 'Not Applicable')], default='NO', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_item_compliances', to='organizations.institution')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_compliances', to='proformas.proformaitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PG Item Compliance',
                'verbose_name_plural': 'PG Item Compliances',
                'unique_together': {('institution', 'item')},
            },
        ),
    ]
