# Generated by Django 5.2.9 on 2025-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaitem',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='implementation_criteria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='importance_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='is_licensing_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='max_score',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='required_evidence_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='requirement_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='weightage_percent',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='proformasection',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proformasection',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proformasection',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proformatemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proformatemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
